version: 2
jobs:
  build:
    docker:
      - image: docker.uncharted.software/distil-build:latest
        auth:
          username: $UNCHARTED_DOCKER_USERNAME
          password: $UNCHARTED_DOCKER_PW
    working_directory: /go/src/github.com/unchartedsoftware/distil-ingest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fb:7f:1c:95:48:cd:e3:b6:eb:7d:c3:1c:fc:b4:06:e8"
      - run:
          name: build app binary
          command: /bin/sh -c "dep ensure -v;go build -i ./cmd/distil-ingest && go build -i ./cmd/distil-merge"



